all:
  hosts:
    server1:
      ansible_host: 192.168.56.11
    client1:
      ansible_host: 192.168.56.12            
  vars:
    default_mem: 512
    default_cpu: 1
    default_base_box: "bento/centos-7.2" #"bento/debian-9"
